#!/usr/bin/env bash
# agentified :: tinyproxy configuration rendering.

# ag_render_proxy_conf MODE PORT FILTER_PATH LOG_PATH PID_PATH
#
# The mode split matters more than it looks. tinyproxy's `Filter` file is an
# allowlist only when `FilterDefaultDeny Yes`; with `No` the very same file
# becomes a *blocklist*. So learn mode cannot simply flip FilterDefaultDeny —
# that would block precisely the hosts we meant to permit. Learn mode omits the
# filter directives entirely and relies on `LogLevel Connect` for observation.
ag_render_proxy_conf() {
  local mode="${1-}" port="${2-}" filter="${3-}" log="${4-}" pid="${5-}"

  case "$mode" in
    enforce|learn|off) ;;
    *) ag_die "unknown mode: '$mode'"; return 1 ;;
  esac
  ag_valid_port "$port" || { ag_die "invalid proxy port: '$port'"; return 1; }

  cat <<EOF
# Generated by agentified. Do not edit; edit /etc/agentified/config instead.
Port $port
Listen 127.0.0.1
Bind 0.0.0.0
User agentproxy
Group agentproxy
Timeout 600
MaxClients 100

Allow 127.0.0.1

PidFile "$pid"
LogFile "$log"
LogLevel Connect

# Without these, CONNECT to :22 would tunnel SSH straight through the proxy.
ConnectPort 443
ConnectPort 80
EOF

  if [ "$mode" = "enforce" ]; then
    cat <<EOF

FilterDefaultDeny Yes
Filter "$filter"
FilterExtended On
FilterCaseSensitive Off
EOF
  else
    cat <<EOF

# mode=$mode: every request is permitted and logged. Run
#   sudo agentified learn
# to turn the log into an allowlist.
EOF
  fi
  return 0
}
